[package]
name = "aws-rust-serverless-oltp"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1.8.13"
aws-sdk-dynamodb = "1.104.0"
lambda_runtime = "1.4.0"
log = "0.4.34"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
simple_logger = "5.2.0"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.26.1", features = ["v4"] }
